;;; mindre-nineties-theme.el --- mindre-nineties theme

;;; Code:

(deftheme mindre-nineties
  "mindre-nineties theme")

(custom-theme-set-faces
 'mindre-nineties
 '(cperl-nonoverridable-face ((t (:inherit font-lock-keyword-face))))
 '(erc-timestamp-face ((t (:foreground "black" :bold t))))
 '(erc-prompt-face ((t (:foreground "black"))))
 '(message-header-name ((t (:foreground "black" :bold t))))
 '(notmuch-message-summary-face ((t (:background "gray90"))))
 '(eshell-prompt ((t (:foreground "black"))))
 '(default ((t (:background "light gray" :foreground "black"))))
 '(cursor ((t (:background "black"))))
 '(border ((t (:foreground "black"))))
 '(sh-quoted-exec ((t (:foreground "dark violet"))))
; '(blue ((t (:foreground "blue"))))
 '(link ((t (:foreground "medium blue" :underline t))))
 '(org-agenda-structure ((t (:foreground "black"))))
 '(org-agenda-date-today ((t (:foreground "medium blue" :underline t))))
 '(org-imminent-deadline ((t (:foreground "red3"))))
 '(org-todo ((t (:foreground "red4"))))
 '(org-done ((t (:foreground "green4"))))
 '(org-headline-done ((t (:foreground "black"))))
 '(bold ((t (:bold t))))
 '(bold-italic ((t (:italic t :bold t))))
 '(border-glyph ((t (nil))))
 '(custom-button-face ((t (:bold t))))
 '(custom-changed-face ((t (:background "blue" :foreground "white"))))
 '(custom-documentation-face ((t (nil))))
 '(custom-face-tag-face ((t (:underline t))))
 '(custom-group-tag-face ((t (:underline t :foreground "blue"))))
 '(custom-group-tag-face-1 ((t (:underline t :foreground "red"))))
 '(custom-invalid-face ((t (:background "red" :foreground "yellow"))))
 '(custom-modified-face ((t (:background "blue" :foreground "white"))))
 '(custom-rogue-face ((t (:background "black" :foreground "pink"))))
 '(custom-saved-face ((t (:underline t))))
 '(custom-set-face ((t (:background "white" :foreground "blue"))))
 '(custom-state-face ((t (:foreground "dark green"))))
 '(custom-variable-button-face ((t (:underline t :bold t))))
 '(custom-variable-tag-face ((t (:underline t :foreground "blue"))))
 '(dired-face-boring ((t (:foreground "Gray65"))))
 '(dired-face-directory ((t (:bold t))))
 '(dired-face-executable ((t (:foreground "SeaGreen"))))
 '(dired-face-flagged ((t (:background "LightSlateGray"))))
 '(dired-face-marked ((t (:background "PaleVioletRed"))))
 '(dired-face-permissions ((t (:background "grey75" :foreground "black"))))
 '(dired-face-setuid ((t (:foreground "Red"))))
 '(dired-face-socket ((t (:foreground "magenta"))))
 '(dired-face-symlink ((t (:foreground "cyan"))))
 '(font-lock-builtin-face ((t (:foreground "medium blue"))))
 '(font-lock-comment-face ((t (:foreground "DarkSlateGray"))))
 '(font-lock-constant-face ((t (:foreground "black"))))
 '(font-lock-doc-string-face ((t (:foreground "green4"))))
 '(font-lock-function-name-face ((t (:foreground "black" :bold t))))
 '(font-lock-keyword-face ((t (:foreground "black" :bold t))))
 '(font-lock-preprocessor-face ((t (:foreground "red3"))))
 '(font-lock-reference-face ((t (:foreground "red3"))))
 '(font-lock-string-face ((t (:foreground "dark green"))))
 '(font-lock-type-face ((t (:foreground "medium blue"))))
 '(font-lock-variable-name-face ((t (:foreground "black"))))
 '(font-lock-warning-face ((t (:bold t :foreground "Red"))))
 '(green ((t (:foreground "green"))))
 '(gui-button-face ((t (:background "grey75" :foreground "black"))))
 '(gui-element ((t (:background "Gray80"))))
; '(highlight ((t (:background "cadet blue"))))
 '(highlight ((t (:background "honeydew3"))))
; '(highlight ((t (:background "wheat"))))
 '(info-node ((t (:italic t :bold t))))
 '(info-xref ((t (:bold t))))
 '(isearch ((t (:background "paleturquoise"))))
 '(italic ((t (:italic t))))
 '(left-margin ((t (nil))))
 '(list-mode-item-selected ((t (:background "gray68"))))
 '(mode-line ((t (:background "Gray80" :box (:style released-button)))))
 '(mode-line-inactive ((t :background "gray80" (:box (:line-width -1 :color "gray75" :style nil)))))
 '(mode-line-buffer-id ((t (:foreground "blue4"))))
 '(mode-line-mousable ((t (:background "gainsboro" :foreground "firebrick"))))
 '(mode-line-mousable-minor-mode ((t (:background "gainsboro" :foreground "green4"))))
 '(header-line ((t (:background "gray85"))))
 '(paren-blink-off ((t (:foreground "gray80"))))
 '(paren-match ((t (:background "cadet blue"))))
; '(show-paren-match ((t (:background "dark cyan"))))
 '(paren-mismatch ((t (:background "DeepPink" :foreground "black"))))
 '(pointer ((t (nil))))
 '(primary-selection ((t (:background "gray75"))))
 '(red ((t (:foreground "red"))))
 '(region ((t (:background "gray75"))))
 '(right-margin ((t (nil))))
 '(secondary-selection ((t (:background "paleturquoise"))))
 '(text-cursor ((t (:background "Red3" :foreground "gray80"))))
 '(toolbar ((t (:background "Gray80"))))
 '(underline ((t (:underline t))))
 '(vertical-divider ((t (:background "Gray80"))))
 '(widget-button-face ((t (:bold t))))
 '(widget-button-pressed-face ((t (:foreground "red"))))
 '(widget-documentation-face ((t (:foreground "dark green"))))
 '(widget-field-face ((t (:background "gray85"))))
 '(widget-inactive-face ((t (:foreground "dim gray"))))
 '(yellow ((t (:foreground "yellow"))))
 '(zmacs-region ((t (:background "gray65"))))
 '(fringe ((t (:background "gray65")))))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
	       (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'mindre-nineties)

;;; mindre-nineties-theme.el ends here
